version: '3.8'

services:
  frontend:
    image: node:18
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - 3000
    ports:
      - 3000:3000
    command: sh -c 'yarn && yarn dev'
  